#!/usr/bin/env python3
"""Generate a portable plugin from the five canonical skills; never edit generated copies."""
import argparse
import hashlib
import json
import shutil
from pathlib import Path
from resolve_module import resolve_modules


def build_plugin(out):
    core=Path(__file__).resolve().parents[1]
    resolved=resolve_modules(core)
    shared=Path(resolved['shared'])
    registry=json.loads((shared/'routing.json').read_text(encoding='utf-8'))
    names=[m['name'] for m in registry['modules']]
    missing=[n for n in names if n not in resolved['modules']]
    if missing:raise ValueError('Missing modules: '+', '.join(missing))
    out=Path(out).resolve()
    if out.exists():raise ValueError('Output must be a new path; preserve existing packages')
    for name in names:
        if out.is_relative_to(Path(resolved['modules'][name]).resolve()):
            raise ValueError('Output cannot be inside a source skill')
    out.mkdir(parents=True)
    shutil.copy2(core/'assets/plugin.json',out/'plugin.json')
    shutil.copytree(shared,out/'shared')
    for name in names:
        source=Path(resolved['modules'][name]);dest=out/'skills'/name
        shutil.copytree(source,dest,ignore=shutil.ignore_patterns('shared','__pycache__','*.pyc'))
        if name=='financial-statement-analysis':
            for f in dest.rglob('*.md'):
                text=f.read_text(encoding='utf-8')
                if f==dest/'SKILL.md':text=text.replace('](shared/','](../../shared/')
                elif f.parent==dest/'references':text=text.replace('](../shared/','](../../../shared/')
                f.write_text(text,encoding='utf-8')
    # Inspect links and pin generated bytes; this is an output index, not a source of rules.
    import re
    for f in out.rglob('*.md'):
        for link in re.findall(r'\]\(([^)]+)\)',f.read_text(encoding='utf-8')):
            if '://' in link or link.startswith('#'):continue
            target=(f.parent/link.split('#')[0]).resolve()
            if not target.exists():raise ValueError('Broken package link: '+str(f)+' -> '+link)
    hashes={str(f.relative_to(out)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(out.rglob('*')) if f.is_file()}
    (out/'build-index.json').write_text(json.dumps({'generated':True,'files':hashes},indent=2)+'\n')
    return {'out':str(out),'modules':names,'files':len(hashes),'status':'built_not_registered'}


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--out',required=True);a=p.parse_args()
    print(json.dumps(build_plugin(a.out),ensure_ascii=False,indent=2))

if __name__=='__main__':main()
